### ISSUE TITLE
Multiple API Key support

### ISSUE THREAD

**Issue by softsimon** [opennodedev/opennode-node#1]
Great lib, made my implementation easier.

I noticed that OpenNode require you to create one unique API key for each of their 3 permissions (READ, INVOICE and WITHDRAW) which require me to run "setCredentials()" to reset the global api_key variable before each request.

Maybe the lib should support the setting of 3 different api-keys, (one per permisson) and let each method use the required key depending on the method. Now if you set just the main key with a Invoice-permission you only get Permission denied from the OpenNode API anyway if you try to execute a withdrawal.

Thanks!

**Comment by joaodealmeida** [comment]
Hello Simon,

You can use the withdrawal key to create/view charges and create/view withdrawals.

**Comment by softsimon** [comment]
> Hello Simon,
> 
> You can use the withdrawal key to create/view charges and create/view withdrawals.

Thank you. Wasn't aware. Ignore my request and thanks a lot!
