### ISSUE TITLE
Missing import 'crypto'

### ISSUE THREAD

**Issue by softsimon** [opennodedev/opennode-node#2]
Calling signatureIsValid resulted in
`ReferenceError: crypto is not defined`

Is the crypto import missing?
`const crypto = require('crypto');`

Running Node 11.6.0

**Comment by joaodealmeida** [comment]
You're right, thanks for finding it out.
I added a new test as well.

https://github.com/opennodedev/opennode-node/commit/e09efd67345b98ecc936f0178943f32ab916cefb

**Comment by gravyplaya** [comment]
Is there a solve to this as im getting the same error. 
 ERROR in ./node_modules/opennode/src/lib.js
 Module not found: Error: Can't resolve 'crypto'

**Comment by joaodealmeida** [comment]
What version of node are you using ?
