### ISSUE TITLE
Support for Multiple API Keys / Clients

### ISSUE THREAD

**Issue by djseeds** [opennodedev/opennode-node#6]
Hi OpenNode team, cool product and library.

I'm working on an app that will use multiple OpenNode connections for multiple users -- as far as I can tell this library only supports a single connection w/ a single API key. Other similar libraries (e.g. https://github.com/btcpayserver/node-btcpay) are class-based so you can have multiple instances of their client, allowing this sort of integration.

Would you be open for a contribution allowing for this type of usage?

**Comment by joaodealmeida** [comment]
Hello djseeds, sorry for the late response but the LN Conf took us away a lot of our tkme. This is actually something we’ve been thinking to do for a while, just didn’t have enough bandwidth for it and had other priorities.


I’ll review your PR and make sure it is backwards compatible. If everything is good there should be no problems in merging it.

**Comment by djseeds** [comment]
Hey @joaodealmeida, thanks for taking a look at this! I figured you guys were busy with lnconf, so no worries. I tried to maintain backwards compatibility and keep tests passing -- let me know if there's anything you want done in a different way.

**Comment by joaodealmeida** [comment]
Looks good! Could you add a test for when you create a new instance and set the credentials?

**Comment by djseeds** [comment]
Yeah sure, let me know if the test I just added is what you were looking for. I didn't know what credentials to use for the second credentials so I used my dev credentials and a test charge. Let me know if there are other credentials you want to use in the test.
